apiVersion: v1
kind: Service
metadata:
  name: downloadservice
  labels:
    app: downloadservice
    service: downloadservice
spec:
  ports:
  - port: 5005
  selector:
    app: downloadservice
   

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: downloadservice
  labels:
    app: downloadservice
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: downloadservice
  template:
    metadata:
      labels:
        app: downloadservice
        version: v1
    spec:
      containers:
      - name: downloadservice
        image: 11shobhit/download-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5005
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: downloadservice-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: downloadservice
spec:
  hosts:
  - "*"
  gateways:
  - downloadservice-gateway
  http:
  - match:
    - uri:
        prefix: "/download"
    route:
    - destination:
        host: downloadservice
        # port:
        #   number: 5005

