
apiVersion: v1
kind: Service
metadata:
  name: opademoservice
  labels:
    app: opademoservice
    service: opademoservice
spec:
  ports:
  - port: 5051
    name: http
  selector:
    app: opademoservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opademoservice
  labels:
    app: opademoservice
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opademoservice
      version: v1
  template:
    metadata:
      labels:
        app: opademoservice
        version: v1
    spec:
      containers:
      - name: opademoservice
        image: 11shobhit/opa-demo-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5051
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: demoservice-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: demoservice
spec:
  hosts:
  - "*"
  gateways:
  - demoservice-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: opademoservice
